- README.md
- app/runner/runner.go
- app/runner/runner_test.go
- app/runner/testdata/conf.yml
If `cmd.options.ignore_errors` set to true error in this cmd won't terminate task on error, but rather will report and continue
resolves #5
> Add support for ignore_errors option

- README.md
- app/config/config.go
- app/config/config_test.go
- app/main_test.go
- app/runner/runner.go
- app/runner/testdata/conf2.yml
This PR treats any multiline `script` as a shell file, i.e. it makes a temp sh file, upload it to the remote host and executes. After execution completed (or failed) that temp script get removed
> Script as the regular sh file

- README.md
- app/executor/executor.go
- app/executor/executor_test.go
- app/executor/local.go
- app/executor/local_test.go
- app/executor/remote.go
- app/executor/remote_test.go
- app/main.go
- app/main_test.go
- app/runner/runner.go
- app/runner/runner_test.go
- app/runner/testdata/conf-local-failed.yml
add support of `-v` / `--verbose`. In this mode, `spot` will output the command executed on remote/local as well as stdout/stderr
> Verbose mode

- app/main.go
In docs there is stated:
* `Defaults to spot.yml`
* `You can also set the environment variable $SPOT_FILE` 
( https://github.com/umputun/simplotask/blob/7db4a2cff0c8b00101997f1ae3fcdc9d4539d604/README.md?plain=1#LL43C60-L43C82 ) 
But it is not true in the code. This pull request corrects the code to aligned with the documentation.
> Using spot.yml & SPOT_FILE in code

- README.md
- app/config/config.go
- app/config/config_test.go
- app/config/testdata/bad-format.yml
- app/config/testdata/hosts
- app/runner/testdata/conf.yml
- app/runner/testdata/conf2.yml
- spot-example.yml
This PR adds support of inventory groups. Groups are optional, and "plain" (groupless) files without still supported
i.e. the oll format like this, sill valid:
```text
h1.example.com 
h2.example.com:2222
h3.example.com:2223 user2
```
in addition, ini-style groups can be defined:
```text
[gr1]
h1.example.com 
h2.example.com:2222
[gr2]
h3.example.com:2223 user2
```
PR also changes the inventory format for both `inventory_file` and `inventory_url` to support groups, i.e.
`inventory_file: {location: "testdata/inventory", groups: ["staging"]}`
> Inventory groups

- README.md
- app/main.go
- app/main_test.go
resolves #17 
The change allows passing `--target` or `-d` multiple times to run tasks for multiple target groups or target hosts. This makes `--host` option fully redundant, and I have removed it.
> support multiple targets in cli, drop hosts override param as redundant

- README.md
`--host` was removed from code in https://github.com/umputun/simplotask/pull/19, here I'm removing it from README.md
> Removed --host from README.md

- README.md
- app/config/config.go
- app/config/config_test.go
- app/main.go
- app/main_test.go
This PR adds a new cli flag`--cmd`, allowing to execute a command directly on remote hosts without a playbook or inventory.
```
> spot -d dev1.umputun.dev -d dev2.umputun.dev  --cmd="ls -a /tmp"
simplotask latest
[dev1.umputun.dev:22] run task ad-hoc, commands: 1
[dev1.umputun.dev:22] > sh -c "ls -a /tmp"
[dev1.umputun.dev:22] > .
[dev1.umputun.dev:22] > ..
[dev1.umputun.dev:22] > .ICE-unix
[dev1.umputun.dev:22] > .X11-unix
[dev1.umputun.dev:22] > mc-root
[dev1.umputun.dev:22] completed ad-hoc {script: sh -c "ls -a /tmp"} (11ms)
[dev1.umputun.dev:22] completed task ad-hoc, commands: 1
[dev2.umputun.dev:22] run task ad-hoc, commands: 1
[dev2.umputun.dev:22] > sh -c "ls -a /tmp"
[dev2.umputun.dev:22] > .
[dev2.umputun.dev:22] > ..
[dev2.umputun.dev:22] > .ICE-unix
[dev2.umputun.dev:22] > …
```
> Adhoc commands

- README.md
- app/config/config.go
- app/config/config_test.go
- app/config/testdata/playbook-with-inventory.yml
- app/main.go
- app/main_test.go
- spot-example.yml
This change simplifies the whole inventory-related logic and makes it work more predictable. Docs updated too
> make much simpler config parsing, see #31

- README.md
- app/config/config.go
- app/config/config_test.go
the idea from [this discussion](https://github.com/umputun/spot/discussions/31#discussioncomment-5774743) by @bessarabov
It adds tags to all places with `[]Destination` i.e. the list of hosts or inventory and matches `--target` by tag, in addition to all the other matches. I have added a section to [README.md](https://github.com/umputun/spot#target-selection] explaining the matching order
> add support of tags in inventory or hosts and match as destinations

- README.md
- app/config/config.go
- app/config/config_test.go
As proposed  by @bessarabov in https://github.com/umputun/spot/discussions/31, I have added "names" type to targets, i.e.
```
targets:
prod:
names: ["h1", "h2"]
```
This will match to names of hosts, i.e. `name` field from the inventory
> add names type of targets

- README.md
- app/main.go
- app/main_test.go
This is the continuation of PR https://github.com/umputun/spot/pull/29 (the previous one was closed, because I have deleted my fork bessarabov/simplotask to make new fork bessarabov/spot)
> Renamed --file to --playbook & SPOT_FILE to SPOT_PLAYBOOK

- app/main.go
Tiny addition to `--help`. Now there is no info about env variable in `--help`:
```
$ spot --help
spot v0.9.1-0aa555f-2023-05-02T08:06:47Z
Usage:
spot [command]
Application Options:
-p, --file=       playbook file (default: spot.yml) [$SPOT_FILE]
-t, --task=       task name
-d, --target=     target name (default: default)
-c, --concurrent= concurrent tasks (default: 1)
--timeout=    ssh timeout (default: 30s)
-i, --inventory=  inventory file or url
-u, --user=       ssh user
-k, --key=        ssh key
-e, --env=        environment variables for all commands
--skip=       skip commands
--only=       run only commands
--dry         dry run
-v, --verbose     verbose mode
--dbg         debug mode
-h, --help        show help
Arguments:
command:          run ad-hoc command on target hosts
``` …
> Added info about env SPOT_INVENTORY to --help

- README.md
- app/config/command.go
- app/runner/runner.go
- app/runner/runner_test.go
- app/runner/testdata/conf.yml
This PR adds `mcopy` command type, which is a list of current `copy` commands, i.e
```yml
- name: copy many files
mcopy:
- {src: file1, dst:/srv/file1}
- {src: file2, dst:/srv/file2}
```
This seems to be a task we may need often, and the current solution with multiple copy commands can be too long if many files involved
> support of mcopy command type

- README.md
- app/config/command.go
- app/config/command_test.go
- app/config/playbook.go
- app/runner/runner.go
- app/runner/runner_test.go
- app/runner/testdata/conf-simple.yml
This PR provides a custom unmarshaler for the command. The goal is to allow to use of either a single element or list in `copy` 
```yml
copy: {src: "f1", "dst":f2}
copy:
- {src: "f10", "dst":f20}
- {src: "f11", "dst":f21}
```
The `mcopy` still exists, so it can be used the same as before. Internally this custom unmarshaler fills either `Copy` or `MCopy` fields, so this custom magic is isolated to the config parser only, and other parts of the system just see the regular `Copy` and `MCopy` fields
> Cmd custom unmarshaler

- app/executor/local.go
- app/executor/local_test.go
- app/executor/remote.go
- app/executor/remote_test.go
- app/executor/testdata/data.txt
- app/executor/testdata/data1.txt
- app/executor/testdata/data2.txt
This PR allows using glob patterns as src in copy/mcopy command. in this case dst should be directory
Implemented for both remote and local executors
> Glob support

- README.md
- pkg/config/command.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
- pkg/runner/testdata/conf.yml
This PR addresses #60 and introduces the `options.sudo` field, allowing users to run `script` commands with elevated privileges. However, this implementation is limited, as enabling sudo for `copy` and `mcopy` commands is significantly more complex. It would require copying files to a temporary location and then executing a move command to transfer them to their final destination. Additionally, supporting glob patterns further complicates the task. Implementing sudo for the sync command is unclear, and how this could be achieved is not immediately apparent.
Considering these limitations, restricting the `sudo` option to the `script` command type is a reasonable trade-off. If users need to deploy substantial resources to root-only locations, using the root user directly is likely more …
> simple sudo implementation

- README.md
- pkg/config/command.go
- pkg/config/command_test.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
- pkg/runner/testdata/conf.yml
This pr related to #62 and discussion #60 
It adds support of `sudo:true` options for all copy (single/multi and `mcopy`) and to delete (both single file and recursive) as well as to `wait` command
_The only command left without sudo support is `sync` and i don't have a good idea how this one can be done_
> Add sudo support to copy, mcopy, delete and wait

- README.md
- pkg/config/command.go
- pkg/config/command_test.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
- pkg/runner/testdata/conf.yml
This PR adds ability to export some variables in one command and get it from env of the another command. From user's point of view this should be expected behavior and it feels like all the commands run in the same shell script. However, internally command detects all the exports inside the script and append result of evaluation of those variables to the end of the executed script as `echo setvar foo=bar`
After the command executed those `setvar` extracted and set to all other commands as a regular env.
This snippet indicates the possible use-case:
```yml
- name: some command
script: |
export foo=$((1 + 2 + 3))
export bar=$((4 + 5))
export baz=zzzzz
ls -laR /tmp
du -hcs /srv
cat /tmp/conf.yml
echo all good, 123
- name: user variables
script: |
env
echo "var foo: ${foo}"
echo "var bar: …
```
> implement support of passing all exported vars to other commands

- cmd/spot/main.go
Here is what `--help` output now:
```
besarabov@bessarabov-osx:~/git/spot/cmd/spot$ ./spot --help
spot latest
Usage:
spot [OPTIONS] [command]
Application Options:
-p, --playbook=                              playbook file (default: spot.yml) [$SPOT_PLAYBOOK]
--task=                                  task name
-t, --target=                                target name (default: default)
-c, --concurrent=                            concurrent tasks (default: 1)
--timeout=                               ssh timeout (default: 30s) [$SPOT_TIMEOUT]
-i, --inventory=                             inventory file or url [$SPOT_INVENTORY]
-u, --user=                                  ssh user
-k, --key=                                   ssh key
-e, --env=                                   environment …
```
> Removed duplicates from --help

- README.md
- pkg/config/playbook.go
- pkg/config/playbook_test.go
This PR supports users in direct target address, i.e `user@example.com:22`
see #73
> Allow user in target address

- README.md
The simplified readme example has a minor typo which always results to "playbook loaded with 0 tasks"
> Fix simplified targets key in readme

- pkg/config/playbook.go
- pkg/config/playbook_test.go
- pkg/config/testdata/simple-playbook-no-inventory.yml
This PR treats all targets set in a simplified playbook as addresses in case inventory is not set. See discussion in #75
> don't treat targets set in simple pb as names if no inventory set

- pkg/config/command.go
- pkg/config/playbook.go
- pkg/config/target.go
- pkg/config/target_test.go
This PR doesn't change functionality but refactors code dealing with target->destination(s) resolution. This is done to keep the code understandable and maintainable. It also adds tests for the various cases in this area
> Targets refactor

- README.md
- cmd/spot/main.go
- cmd/spot/main_test.go
- pkg/config/playbook.go
Add new task-level filed `targets`.
It will be used only in case no `-t/--target` is set in the command line. Technically, `-t` always set as it has a default target `default`; however, this PR considers such default as non-set and will use task.targets 
This is what it looks like in the playbook:
```yml
targets:
prod:
hosts: [{host: "h1.example.com", user: "test"}, {"h2.example.com", "port": 2222, name: "h2"}]
staging:
groups: ["staging"]
tasks:
- name: task1
targets: ["dev", "host3.example.com:2222"]
commands:
- name: command1
script: echo "Hello World."
```
targets inside the task resolved the same way as targets defined in the command line, i.e. all the sequence of matching groups, tags, names, etc...
The reason why this may be handy is the ability to make a playbook with multiple …
> add support of task's targets set directly in playbook

- README.md
- pkg/config/command.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
This adds a new option to the command allowing limit a particular command to run on a particular host(s). This is somewhat similar to #85 but works on the command level, and limits can be hostname or address. It also allows reverse the condition with `!` prefix, meaning "only on other hosts".
Not something I would often use, as I'd rather make a separate task for such commands, but in some cases can be handy. For example, running a simplified playbook and wanting some command to initialize only one of the destination hosts in a special way
> add cmd option "only_on" allowing to limit on what host

- README.md
- cmd/spot/main.go
- cmd/spot/main_test.go
- cmd/spot/testdata/conf-dynamic.yml
- pkg/config/playbook.go
- pkg/config/playbook_test.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
This PR adds support for dynamic targets in some limited use cases.
```yaml
tasks:
- name: get host
targets: ["default"]
script: |
export thehost=$(curl -s http://example.com/next-host)
options: {local: true}
- name: run on host
targets: ["$thehost"]
script: |
echo "doing something on $thehost"
```
This example indicates the essence of the change. Here the exported variables that are usually available for all the commands in the task will be available for all task targets and `targets: ["$thehost"]` will be evaluated
> A practical use case for dynamic targets arises during the provisioning of a new host, followed by the execution of commands on it. Since the IP address of the new host isn't known beforehand, dynamic retrieval becomes essential.
> Dynamic targets

- README.md
- pkg/config/command.go
- pkg/config/command_test.go
- pkg/runner/commands.go
- pkg/runner/commands_test.go
- pkg/runner/runner.go
implements #89 
This PR adds a new command field, `cond`. This is an optional condition, which is a single or multiline script. The command will be executed only if the condition script returns 0. If the condition is not set, the command will be executed right away, like before this change.
> add condition for script to execute

- README.md
- pkg/config/command.go
- pkg/config/command_test.go
- pkg/runner/commands.go
- pkg/runner/commands_test.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
- pkg/runner/testdata/conf.yml
This is a new command, `echo`. The only goal is to print something to the normal (i.e. non- verbose and non-debug) log. This command is a little bit redundant; currently, it is possible to do just `echo` in a script and see the output in `-v` mode. However, there are use cases where such output is an essential result from the playbook execution, for example, if the playbook made a new resource, like an instance or volume and we need to inform the user what is ip/id of the new resource. For cases like this, I don't want to hide this info behind `-v` flag.
The echo command is `echo` and it is the lowest priority match, i.e. all the existing command will match first before we try to recognize `echo`. In the playbook, this command is as simple as this:
```yaml
- name: show things
echo: …
```
> Echo command

- README.md
- pkg/config/command.go
- pkg/config/command_test.go
- pkg/runner/commands.go
- pkg/runner/commands_test.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
- pkg/runner/testdata/conf.yml
similar to #99 but for delete command
after the change delete can be a list of paths, i.e.
```yml
delete:
- {path: /srv/foo}
- {path: /srv/bar}
```
_The command keeps the single form untouched_
> support multiple delete commands

- README.md
- pkg/config/command.go
- pkg/executor/dry.go
- pkg/executor/dry_test.go
- pkg/executor/executor.go
- pkg/executor/local.go
- pkg/executor/local_test.go
- pkg/executor/remote.go
- pkg/executor/remote_test.go
- pkg/runner/commands.go
- pkg/runner/commands_test.go
This PR partially addresses #77 for the `copy` command. It adds the same default behavior `sync` already had i.e. skipping the copy operation in case the destination file is identical to the source file.
The check works the same way as rsync's default "quick check" and compares file sizes and modification time. Adding checksum support will be done too, some day. 
The check can be suppressed by `force` option
> Copy with check and force mode

- pkg/runner/commands.go
- pkg/runner/commands_test.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
This PR clarifies the running script in verbose mode.  In addition to the temp script name reporting, which is saying little, it also prints the script itself, i.e.
```
[localhost:56404] script: /tmp/.spot/spot-script1960898714
[localhost:56404]  + #!/bin/sh
[localhost:56404]  + set -e
[localhost:56404]  + export foo=$((1 + 2 + 3))
[localhost:56404]  + export bar=$((4 + 5))
[localhost:56404]  + export baz=zzzzz
[localhost:56404]  + ls -laR /tmp
[localhost:56404]  + du -hcs /srv
[localhost:56404]  + cat /tmp/conf.yml
```
All of this affects verbose mode only, for both `script` and `wait` command
> verbose mode output multiline script source and wait list source

- README.md
- pkg/config/command.go
- pkg/config/command_test.go
This is related to https://github.com/umputun/spot/discussions/116#discussioncomment-6087380
The change allows to set of any custom shebang (i.e. `#!/bin/bash`) to define the shell running the script
> allow script to have shebang

- README.md
- cmd/spot/main.go
- pkg/executor/connector.go
- vendor/golang.org/x/crypto/ssh/agent/client.go
- vendor/golang.org/x/crypto/ssh/agent/forward.go
- vendor/golang.org/x/crypto/ssh/agent/keyring.go
- vendor/golang.org/x/crypto/ssh/agent/server.go
- vendor/modules.txt
should address #112
It adds auth with ssh-agent. Pls, note - this is optional with the new param `--ssh-agent` (env: `SPOT_SSH_AGENT`) should be used to enable it. If no key is provided or a key is not found, it will fail back to ssh-agent automatically. 
_This is done to preserve back compatibility and prevent confusion if the user has both key and agent auth at the same time_
> add ssh-agent support 

- README.md
Add reference to YAML multiline string formatting examples/docs for #122
> reference to YAML multiline string formatting examples/docs

- README.md
- cmd/spot/main.go
- cmd/spot/main_test.go
- pkg/secrets/memory_test.go
relatated to https://github.com/umputun/spot/discussions/126
This PR adds basic support for env file in yaml format. The default is `env.yaml` but can be changed in the command line. In case this file is missing, it won't fail and will continue as usual, so the change is back-compatible.
example of env.yml:
```yml
vars:
var1: val1
var2: val2
```
> Support env file

- pkg/executor/remote.go
- pkg/runner/commands.go
- pkg/runner/commands_test.go
- pkg/runner/runner_test.go
The issue described in #129 
This is what happened - spot makes temp directory `/tmp/.spot` with 700 and the active spot's user. This location is used for copy (sudo mode only) and multiline scripts. Both commands clean the temp files but leave the directory. As a result - if ssh user changed, it won't be able to access `/tmp/.spot` anymore.
The fix changes temp directory to a unique one and clean it after command completed
> Unique temp directory for script and copy commands

- pkg/runner/commands.go
- pkg/runner/runner_test.go
- pkg/runner/testdata/conf.yml
This is most likely the reason for issue #139
> prevent single-line sudo command to run in dbl-shell

- .github/workflows/ci.yml
- README.md
- cmd/spot/main.go
- cmd/spot/main_test.go
- cmd/spot/testdata/conf3.yml
Support for multiple `--task` CLI option requested in https://github.com/umputun/spot/issues/131
> Multiple task cli option

- pkg/runner/commands.go
see #138 
This PR replaces os-dependent `filepath.Join` by a simple concatenation with `/` separator.
> enforce linux separator for tmp location

- pkg/config/command.go
- pkg/config/command_test.go
This small PR addresses https://github.com/umputun/spot/issues/144#issuecomment-1653476516
1. Processes shebang on the first line only
2. Strips leading empty string that can be added due to some yaml formats
3. Simplify shebang detection, as it has to be on the first line
> safer script processing 

- README.md
- pkg/config/command.go
- pkg/runner/commands.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
- pkg/runner/testdata/conf.yml
- schemas/playbook.json
The goal is to add a per-task `on_exit` command that will be invoked on the task's completion on each server. The goal is to allow all kinds of cleanup actions, service restarts, and so on to be in a more logical place.
Currently, it is possible to add some cleanup commands, but for larger tasks, it is hard to follow, and having it right in the command should make it easier. 
For example:
```yaml
task:
- name: "copy script"
copy: {src: "testdata/script.sh", "dst": "/tmp/script.sh", "chmod+x": true}
on_exit: "rm -fv /tmp/script.sh" # register deferred action to remove script.sh after execution
- name: "run script"
script: "/tmp/script.sh"
```
Here, we "register" the removal of `/tmp/script.sh`. This is somewhat similar to Go's deffer running the command on function completion, but in the …
> add support for on_exit deferring it for all the commands

- pkg/runner/runner_test.go
Remote docker execution is supported by test containers
However, there are 2 places in SPOT tests where expected `localhost` in runner output failing in case docker is remote DOCKER_HOST=tcp://<IP>:2375
> fix test when DOCKER_HOST=tcp://<IP>:2375 using  remote host

- README.md
- pkg/config/command.go
- pkg/config/command_test.go
- pkg/config/playbook.go
- pkg/config/playbook_test.go
- pkg/config/testdata/with-ssh-shell.yml
This PR adds a new top-level field to playbooks (both full and simplified versions), allowing to set the local shell (i.e. `local_shell=/bin/bash`)
This is because there are unpredictable and unexpected results if we run some scripts with local mode on a different host. For example, this simple script works fine with `#/bin/sh` but doesn't work correctly with `#/bin/zsh`
```
- name: "make images"
script: |
IMAGES="website email-sender private-share"
mkdir -p /tmp/web-images
for image in ${IMAGES}; do
echo "process image: ${image}"
docker pull  example.com/miscs/${image}:latest
docker save "example.com/miscs/${image}" -o "/tmp/web-images/${image}.tar"
done
options: {local: true}
```
The change is back compatible, i.e., if `local_shell` is not set, it will follow the old logic …
> Local shell

- cmd/secrets/main_test.go
- cmd/spot/main.go
- cmd/spot/main_test.go
- pkg/executor/local.go
- pkg/runner/runner_test.go
- pkg/secrets/aws_test.go
should address #170 
If no ssh key is specified and the `--ssh-agent` option is specified, do not select the default key
> Do not select the default key with --ssh=agent

- pkg/runner/runner.go
> fix local dry executor selection

- pkg/runner/commands.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
- pkg/runner/testdata/conf-onerror.yml
see discussion #177 
The change is propagating environment setting as well as secrets from the task triggered onerror call. This is follow the standard way we treat those in `script` command and should be working with both a single line and multiline forms of `onerror`
> extend support of env vars and secrets for onerror command #178

- README.md
- pkg/config/playbook.go
- pkg/config/playbook_test.go
- pkg/config/testdata/playbook-with-task-opts.yml
The initial goal was to allow setting task-level secrets; however, to keep things consistent with other options, it was extended to support all the options. The solution is limited, and command options can't reset the boolean options defined at the task level. This is because we don't have a way to distinguish between default values (i.e. false for bool) and false set for real.
This PR also addresses concerns mentioned by @rahfar in #179 and allows the setting of secrets on the task level, once for all the commands and onerror
> add support for task-level options propagated to all commands

- cmd/spot/main.go
- cmd/spot/main_test.go
- cmd/spot/testdata/conf.yml
- pkg/executor/logger.go
- pkg/executor/logger_test.go
Enforce masking of secrets in internal logger.  Also enforce masking  in colorized log if `Printf` used.
This PR implements the masking of secrets in logger output and revises how debugging is set up, with a focus on logs involving secrets. The secrets are made available only after the playbook is loaded, and they're now passed as parameters to setupLog function. Relevant tests were updated and an additional test case for Printf function with secrets was added.
see #181
> Secret masking improvements 

- README.md
- cmd/spot/main.go
- cmd/spot/main_test.go
The function `envVars` has been updated to enable the application to also read system environment variables, in addition to CLI and env file variables. This change includes an update of the function's comment to reflect the new behavior, and the addition of new test cases to validate the feature. CLI variables override env file variables, which in turn override system environment variables if they share the same name.
see discussion #184
> Add system env variable expansion to envVars function

- README.md
- pkg/runner/commands.go
- pkg/runner/commands_test.go
- site/docs/index.md
Those variables are split from `hostAddr` to `SPOT_REMOTE_ADDR` and `SPOT_REMOTE_PORT`. The documentation has also been updated to reflect these changes.
> add runtime SPOT_REMOTE_ADDR and SPOT_REMOTE_PORT

- README.md
- cmd/spot/main.go
- cmd/spot/main_test.go
- pkg/executor/connector.go
- site/docs/index.md
This pull request introduces the forward-ssh-agent option, allowing users to leverage SSH agent forwarding when executing commands on remote hosts. This facilitates secure authentication by forwarding connections from a local authentication agent, such as ssh-agent, to the remote host. It’s particularly useful in environments where direct SSH access needs to be secured and simplified without exposing private key material.
If it isn't needed or doesn't fit the project's direction, feel free to decline this PR.
> add option to enable agent forwarding

- .golangci.yml
- cmd/spot/main.go
- pkg/runner/commands.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
In this update, a second verbosity level (Verbose2) has been added to the codebase. The normal -v (Verbose) is not reporting the content of the script anymore but -vv (Verbose2) only. Additionally, the verbosity short flag in cmd/spot/main.go has been modified and its type to boolean slice to allow increased verbosity when multiple "v" flags are used.
fix #188
> Add second verbosity level and update related logic

- README.md
- cmd/spot/main.go
- cmd/spot/main_test.go
- cmd/spot/testdata/conf.yml
- pkg/config/command.go
- pkg/config/playbook.go
- pkg/runner/commands.go
- pkg/runner/mocks/playbook.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
see #196
This PR changes the scope of registered variables, making them available to all subsequent tasks. The only thing I still doubt is whether those vars should overwrite locally set variables (set by command) and act as immutable (can be set once). For now, I made them immutable, but may reconsider it if needed.
cc: @koolay
> Allow registered vars to be populated across tasks

- .github/dependabot.yml
There is no need for docker updates as the latest versions of containers are used.
> Add dependabot updates for GitHub Actions and Go modules

- cmd/spot/main.go
- pkg/config/playbook_test.go
- pkg/config/testdata/with-ssh-shell.yml
This regression was introduced some time ago and sets the default SSH shell to `/bin/sh`. This setting is considered the highest priority in CLI overrides, and consequently, it is enforced even if a custom SSH shell is set in the playbook.
fixes #212
> don't set default override for ssh shell #212

- pkg/config/command.go
- pkg/config/command_test.go
Only in case of inline (single command) env
fix #211
> Added export prefix to environment variables

- pkg/executor/remote.go
- pkg/runner/commands.go
- pkg/runner/commands_test.go
this file is uploaded to remote temp and removed properly as a part of returned teardown(). However the local file created first and the removal was missing. 
This PR adds the removal right after the upload done. It also adds a test for the cleanup
see #242
> add missing cleanup for local temp script file

- README.md
- cmd/spot/main.go
- cmd/spot/main_test.go
- pkg/config/command.go
- pkg/config/playbook.go
- pkg/config/playbook_test.go
- pkg/config/testdata/with-ssh-config.yml
- pkg/runner/commands.go
- pkg/runner/commands_test.go
- pkg/runner/runner.go
This commit adds support for specifying a custom SSH temporary directory. It includes:
- New `SSHTempDir` field in PlayBook and Target structs
- Command line flag and environment variable for setting temp dir
- Logic to use custom temp dir in command execution
- Tests for new functionality
- Update documentation and examples
> Add custom SSH temp directory option

- cmd/secrets/main_test.go
- cmd/spot/main_test.go
- pkg/config/command.go
- pkg/config/command_test.go
- pkg/config/deepcopy/deepcopy.go
- pkg/config/deepcopy/deepcopy_test.go
- pkg/config/playbook_test.go
- pkg/runner/commands.go
- pkg/runner/commands_test.go
- pkg/runner/runner_test.go
- pkg/runner/testdata/register_templates.yml
- pkg/secrets/ansible_vault.go
- pkg/secrets/spot_test.go
- Added ability to use template variables in register directives
- Fixed environment variable expansion in script preparation and register variable matching
- Implemented substitution for both predefined SPOT vars and environment variables
- Added test files to verify that expanded variable names match correctly
Fixes #261
> Support dynamic register variable names with templating #261

- .github/workflows/ci.yml
- .gitignore
- .golangci.yml
- cmd/secrets/main.go
- pkg/executor/logger.go
- pkg/executor/logger_test.go
This PR fixes the issue where secrets containing special characters or periods weren't being properly masked in logs (#282).
- Updated the secrets masking regex pattern to properly handle secrets with special characters
- Added an `isAlphanumeric` helper function to determine when to use word boundaries vs. direct pattern matching
- Added comprehensive test cases to verify the fix works for all cases reported in the issue
- Fixed linter warnings in various files to comply with golangci-lint v2
- Updated GitHub workflow to use the latest golangci-lint action (v7) with version v2.1.5
Fixes #282
> Fix secrets masking for special characters

- README.md
- pkg/config/command.go
- pkg/config/command_test.go
- pkg/executor/logger.go
- pkg/executor/logger_test.go
- site/docs/index.md
- Automatically protect positional parameters (`$0`-`$9`) from shell expansion
- Add support for escaped dollar (`\$`) to create literal dollar signs
- Preserve normal variable expansion for `$HOME`, `${USER}`, etc.
As reported in #285, environment variables containing positional parameters (like bcrypt hashes with `$2a$14$...`) were being corrupted by shell expansion. Additionally, there was no way to create literal dollar signs in environment values.
The fix detects positional parameters and escaped dollars, then uses single quotes to prevent expansion for those values while keeping double quotes for normal variables.
```yaml
env:
BCRYPT: "$2a$14$G.j2F3fm9wluTougUU52sOzePOvvpujjRrCoVp5qWVZ6qRJh58ISC"
LITERAL: "\$HOME"
HOME_DIR: "$HOME"
```
1. Modified `formatEnvVar()` in …
> Fix environment variable expansion issues

- pkg/config/playbook_test.go
- pkg/config/target_test.go
- Added comprehensive test coverage for empty group handling in inventory
- Tests ensure the current graceful behavior is preserved and documented
As discussed in #302, Spot currently handles empty groups gracefully:
- Empty groups can exist in inventory without causing errors
- When targeting only empty groups, an appropriate error is returned
- Mixed empty and populated groups work correctly
This PR adds tests to ensure this behavior is maintained.
- Added tests in `pkg/config/target_test.go` for various empty group scenarios
- Added tests in `pkg/config/playbook_test.go` for direct empty group targeting
- All tests pass, confirming current behavior
The new tests cover:
1. **Empty groups only** - Confirms error when no hosts found
2. **Mixed empty and populated groups** - Only populated …
> Add tests for empty groups in inventory

- CLAUDE.md
- Makefile
- cmd/spot/main.go
- Added `-s` as a short flag for the `--skip` option to match user expectations and common CLI conventions
- Fixed Makefile `site` target to properly handle directory removal with `rm -rf`
- Updated documentation generation command in CLAUDE.md to use `make prep-site`
- Added rule to never include test plans in PR descriptions
Related #308
> Add short flag -s for --skip option

- README.md
- pkg/config/command.go
- pkg/runner/commands.go
- pkg/runner/commands_test.go
- schemas/playbook.json
- Implements sudo password authentication using the existing secrets infrastructure
- Adds secure password piping to sudo commands using `printf | sudo -S` pattern
- Prevents shell injection vulnerabilities with proper escaping
- Added `sudo_password` field to `CmdOptions` to specify which secret contains the sudo password
- Created `wrapWithSudo()` helper method to centralize all sudo command wrapping logic
- Updated all command types (script, copy, delete, wait, echo, line) to use the secure helper
- Added comprehensive test coverage including passwords with special characters
- Updated README with usage examples and security considerations
- Updated JSON schema to include new configuration fields
The implementation uses `printf '%s\n' 'password' | sudo -S command` pattern which:
- …
> feat: add sudo password support via secrets
